USE bdNovaTurma

INSERT INTO tb2A (nomeAluno, statusAluno)
VALUES 
    ('Sócrates', 'APROVADO'),
    ('Rivellino', 'APROVADO'),
    ('Neto', 'APROVADO'),
    ('Casagrande', 'APROVADO'),
    ('Vampeta', 'APROVADO'),
    ('Tevez', 'APROVADO'),
    ('Marcelinho Carioca', 'APROVADO'),
    ('Ronaldo', 'APROVADO'),
    ('Dida', 'APROVADO'),
    ('Gil', 'APROVADO'),
    ('Ricardinho', 'APROVADO'),
    ('Danilo', 'APROVADO'),
    ('Paulinho', 'APROVADO'),
    ('Cássio', 'APROVADO'),
    ('Fagner', 'APROVADO'),
    ('Jadson', 'APROVADO'),
    ('Romarinho', 'APROVADO'),
    ('Luizão', 'APROVADO'),
    ('Ralf', 'APROVADO'),
    ('Elias', 'APROVADO'),
    ('Sheik', 'DESAPROVADO'),
    ('André Luiz', 'DESAPROVADO'),
    ('Márcio Bittencourt', 'DESAPROVADO'),
    ('Zenon', 'DESAPROVADO'),
    ('Viola', 'DESAPROVADO'),
    ('Mirandinha', 'DESAPROVADO'),
    ('Biro-Biro', 'DESAPROVADO'),
    ('Finazzi', 'DESAPROVADO'),
    ('Douglas', 'DESAPROVADO'),
    ('Zé Elias', 'DESAPROVADO'),
    ('Edilson', 'DESAPROVADO'),
    ('Roger', 'DESAPROVADO'),
    ('Silvinho', 'DESAPROVADO'),
    ('Gamarra', 'DESAPROVADO'),
    ('Batata', 'DESAPROVADO'),
    ('Fabio Baiano', 'DESAPROVADO'),
    ('Carlos Alberto', 'DESAPROVADO'),
    ('Ramalho', 'DESAPROVADO'),
    ('Garro', 'DESAPROVADO'),
    ('Felipe', 'DESAPROVADO')


INSERT INTO tb2B (nomeAluno, statusAluno)
VALUES 
    ('Wladimir', 'APROVADO'),
    ('Basílio', 'APROVADO'),
    ('Fabinho', 'APROVADO'),
    ('Fábio Santos', 'APROVADO'),
    ('Leandro Castán', 'APROVADO'),
    ('Cléber', 'APROVADO'),
    ('Balbuena', 'APROVADO'),
    ('Pedro', 'APROVADO'),
    ('Gustavo', 'APROVADO'),
    ('Dentinho', 'APROVADO'),
    ('Wesley', 'APROVADO'),
    ('Giuliano', 'APROVADO'),
    ('Kai Havertz', 'APROVADO'),
    ('Renato Augusto', 'APROVADO'),
    ('Guerrero', 'APROVADO'),
    ('Mateus Vital', 'APROVADO'),
    ('Arana', 'APROVADO'),
    ('Willian', 'APROVADO'),
    ('Roger Guedes', 'APROVADO'),
    ('Maycon', 'APROVADO'),
    ('Pedrinho', 'DESAPROVADO'),
    ('Yago', 'DESAPROVADO'),
    ('Gil', 'DESAPROVADO'),
    ('Romero', 'DESAPROVADO'),
    ('Lukaku', 'DESAPROVADO'),
    ('Mantuan', 'DESAPROVADO'),
    ('Gabriel', 'DESAPROVADO'),
    ('Jô', 'DESAPROVADO'),
    ('Marllon', 'DESAPROVADO'),
    ('Richard', 'DESAPROVADO'),
    ('Jean', 'DESAPROVADO'),
    ('Uendel', 'DESAPROVADO'),
    ('Douglas Santos', 'DESAPROVADO'),
    ('Ramiro', 'DESAPROVADO'),
    ('Hugo Bota', 'DESAPROVADO'),
    ('Hugo Souza', 'DESAPROVADO'),
    ('Memphis', 'DESAPROVADO'),
    ('Carrillo', 'DESAPROVADO'),
    ('Martinez', 'DESAPROVADO'),
    ('Yuri Alberto', 'DESAPROVADO')